### ISSUE TITLE
How export data to 'copy', 'csv', 'excel', 'pdf', 'print' 

### ISSUE THREAD

**Issue by samqueiroz** [ypnos-web/cakephp-datatables#10]
How export data to 'copy', 'csv', 'excel', 'pdf', 'print'

**Comment by ypnos-web** [comment]
Just follow the example at https://datatables.net/extensions/buttons/examples/initialisation/export.html

1. Make sure that you include all needed Javascript and CSS files.

2. Provide the 'dom' and 'buttons' options from the example above like any other DataTables options as described here:
https://github.com/ypnos-web/cakephp-datatables/wiki/Quick-Start#create-your-table-in-the-template

**Comment by samqueiroz** [comment]
Thanks , I was forgetting to put the "dom".

 $options = [
 ...
'dom'=> 'Bfrtip',
	'lengthMenu'=> [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
	 'buttons'=>[    'copy', 'csv', 'excel', 'pdf', 'print' , 'pageLength']
 ....
