### ISSUE TITLE
Please provide composer link for php < 7

### ISSUE THREAD

**Issue by incredibleX** [ypnos-web/cakephp-datatables#12]
I"d love to use this plugin, but i'm not in a situation to update my server to PHP 7. Please provide the composer link for previous versions.

**Comment by ypnos-web** [comment]
If you would like to do a pull request with a PHP 5.x compliant version of the code I will offer it in a separate branch. It is only few changes overall as the codebase is small.

**Comment by incredibleX** [comment]
Sure please.

**Comment by ypnos-web** [comment]
OK, I am waiting for your pull request. I don't have time to do this myself right now.

**Comment by micdobro** [comment]
Is anyone working on this? If not, then I am willing to "strip" the plugin so that it can run on PHP 5.5.9 (min. required) - and I plan to start basically ASAP. 
From what I can see it's mostly scalar and return type hints - and there could be some traps regarding the Uniform Variable Syntax (and I found also null coalesce operator in a quick review).

**Comment by micdobro** [comment]
PS I have it ready. I was able to render a table (had minor JS hiccups - but using latest js from CDN fixed it). I will continue developing my project - and if everything works I will be more than happy to share.

**Comment by ypnos-web** [comment]
Thank you for the offer, can you do a pull request, I will then maintain in a separate branch.

**Comment by micdobro** [comment]
Yes - please allow a few days more for testing (I have already integrated the plugin and I am hacking some serious tablework here now). Apart from that I'd gladly contribute also to examples in the wiki/doc. If I stumble upon some limitations - you can expect more pull requests from my side.

**Comment by ypnos-web** [comment]
Any contributions to the docs are also highly appreciated, especially as documentation of some features is completely lacking right now.

**Comment by Tartoob** [comment]
Hi,

Here PHP5 version http://www.filedropper.com/datatables-php5

Good Luck

**Comment by ypnos-web** [comment]
Thank you!
@Tartoob I used your file as a base for the new `php5` branch.
@micdobro I am still happy to receive any contributions from your side!

Everybody needing PHP5 support please use the `php5` branch, e.g.:
```json
    "require": {
        "ypnos-web/cakephp-datatables": "dev-php5",
    },

```

**Comment by Tartoob** [comment]
@ypnos-web It works very well, except pagination not working after search. I don't know how to fix it

**Comment by Tartoob** [comment]
Could you please edit read me file, so people would know there is php 5 version
