### ISSUE TITLE
Adding an "actions" column

### ISSUE THREAD

**Issue by lorro** [ypnos-web/cakephp-datatables#13]
Hi,

I'm wondering if it's in any clean way possible to add a non-data column to the datatable through this plugin. For instance I would like to add a column width an "edit" & "delete" link. Or is it only possible to generate a table with data columns only through the plugin?

Before I decided to try the plugin I always coded my "json views" myself so it was easy to put in the columns whatever I wanted, but I wonder how to do this through your plugin.

Thanks :)

**Comment by ypnos-web** [comment]
Custom columns is no problem at all -- just do it the "DataTables way", but setup through the plugin.

1. You can write some static markup in CakePHP (e.g. use `$this->Form->button()` etc.) and ship it through `columns.defaultContent` option:
https://datatables.net/reference/option/columns.defaultContent

Here is an example that connects such static buttons with jQuery: https://datatables.net/examples/ajax/null_data_source.html

2. You can use a Javascript function to fill the content dynamically:
https://github.com/ypnos-web/cakephp-datatables/wiki/Callback-functions (using `columns.render` option)

Me personally, I suggest to use a callback with render option. In the plugin wiki it is very well explained how you can provide additional parameters to the callback function from CakePHP. So you can for example pass a base URL, I18N text etc. to the callback to keep all logic on the server-side, and have a very simple slick solution as the callback function just has these parts as additional parameters (or one parameter object if you want to go array $option style).

An example is the row links callback:
https://github.com/ypnos-web/cakephp-datatables/blob/master/webroot/js/cakephp.dataTables.js#L96

**Comment by ypnos-web** [comment]
@lorro  just to note, I added an example (not tested but should work) to my previous answer.

**Comment by lorro** [comment]
Many thanks for the fast reply :+1: 
Will try this.

**Comment by micdobro** [comment]
Example provided by @ypnos-web is the one that causes no other issues with table actions - I mean everything works as it should with respect to pagination, search etc. In the beginning I tried to do some creative Javascript and reuse ``rowId`` set in the options - but that fails miserable once you search/paginate etc. 
The example works - I arrived at exactly the same code (@ypnos-web this is why I offered adding some stuff to docs - it was especially this bit; my offer is still valid - I am just a bit behind with schedule here).

**Comment by lorro** [comment]
Hi,

I got it working almost like I would like. Just adding buttons or links is working perfectly, and got it to redirect to the correct url.  But I'm struggling to make a "delete" button with the postLink method of the CakePHP FormHelper. Adding the button is no big deal, getting it to work is :)

By using the render method to display a delete button on each seperate row each individual "delete Form" got the exact same form name (that is generated by cakePHP) and of course it should be an unique for each separate form. According to me this is causing the following error:
`Uncaught TypeError: document.post_5798b2e181680319532845.submit is not a function`

Do you perhaps have any advice how we could overcome this? Would prefer to use a postLink instead of a normal link for security purposes of course.

Thanks!

**Comment by micdobro** [comment]
Experimental "loud thinking" - I would probably drop the postLink method from the FormHelper and extend the javascript callback function (that you name via the datatable helper) with a jQuery POST call. Then there still the problem if hiding the row you have just deleted - but that would be just reloading the "current view" of the datatable (provided you are using the ajax backend). If you write it nicely and keep things standard, then you will only have to write this once for all tables in your project (my feeling ;)
