### ISSUE TITLE
Match words out of order not working.

### ISSUE THREAD

**Issue by bedo2991** [ypnos-web/cakephp-datatables#15]
Hi, I don't know if it's really an issue or it's just me that doesn't know how to implement/enable this.

DataTable promises to do this:

"Match words out of order. For example if you search for Allan Fife it would match a row containing the words Allan and Fife, regardless of the order or position that they appear in the table."

But using this plugin it doesn't work like that, looking for "Fife" wouldn't return any record.

Using:
`<script type="text/javascript" src="/DataTables/jQuery-1.12.3/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.6/dt-1.10.12/af-2.1.2/sc-1.4.2/se-1.2.0/datatables.js"></script>`

Any idea on how to allow it? Thanks

**Comment by bedo2991** [comment]
Ok, I've found more or less a solution. Setting 'prefixSearch' to false inside the DataTablesComponent.php at least another word can be found.

protected $_defaultConfig = [
        'start' => 0,
        'length' => 10,
        'order' => [],
        'prefixSearch' => **false**, // use "LIKE …%" instead of "LIKE %…%" conditions
        'conditionsOr' => [],  // table-wide search conditions
        'conditionsAnd' => [], // column search conditions
        'matching' => [],      // column search conditions for foreign tables
    ];

**Comment by ypnos-web** [comment]
`prefixSearch` is the option designated to control the substring search behavior.
You do not need to edit a component to change its options.

Rather, you can pass the options as a parameter to `loadComponent()`. See [CakePHP component documentation](http://book.cakephp.org/3.0/en/controllers/components.html#configuring-components) for more details.

**Comment by bedo2991** [comment]
Thanks for the help, now it's enabled like this:
`$this->loadComponent('DataTables.DataTables',
							 [
							 'prefixSearch'=>false //Searches for %TEXT% instead of TEXT%
							 ]);`
For me this would actually be enough, but  maybe it could be useful for others to reach the behavior that is shown here?
https://datatables.net/
There you can look for "Surname Name" and it would still find it even if the entry is written as "Name Surname". Currently in your plugin you could find it by typing either the name or the surname, but when you keep typing the second one the entry is not found anymore (because the LIKE condition doesn't match anymore).

Thanks again!

**Comment by ypnos-web** [comment]
I would gladly accept a pull request that implements DataTables' client side search behavior server-sided (probably going along the lines of tokenizing the search string and constructing a chain of whereOr() conditions).

You can also implement a custom search behavior in your table's finder. When calling `DataTables->find()`, pass `'delegateSearch' => true` as an option. In your finder implementation, check for and read the query string from the `globalSearch` option.

The DT component also can be used in conjunction with the [Search plugin](https://github.com/FriendsOfCake/search). I am not sure if the latter provides the functionality you seek for out of the box though.
