### ISSUE TITLE
Quick improvement suggestion

### ISSUE THREAD

**Issue by DiegoMax** [ypnos-web/cakephp-datatables#16]
Hello there, just a quick suggestion.

on DataTablesComponent.php change line 195
`$condition = ["{$column} LIKE" => $right];`
to
`$condition = ["{$column} ILIKE" => $right];`

> (notice **ILIKE** as opposed to LIKE)

This will make the searches case insensitive, which is way more useful when searching.

Also, it would be great if you could switch all those internal searching methods from private to protected scope so that they could be overwritten if needed

I would provide you a PR if only i knew how to deal with composer and local repos...
Thanks!
// Diego

**Comment by ypnos-web** [comment]
Hello Diego,

thank you for your suggestions!

1. As far as I know, `ILIKE` is a PostgreSQL extension to the SQL standard and not supported by other databases. We might introduce an optional use of ILIKE that is configurable via config setting, in the same fashion as the `prefixSearch` config option.
2. I agree to make these methods `protected`, however for now I don't see the internal interfaces as stable, so newer versions of the plugin might break code that overwrites these methods.

I am happy to accept PRs for both issues, please make sure to base them off the 'devel' branch.
The use of custom repositories in composer is quite easy. Add this to your composer.json:

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/diegomax/cakephp-datatables"
        }
    ],
```

Then you can use it in require:
```json
    "require": {
        "php": ">=7.0.0",
        …
        "diegomax/cakephp-datatables": "dev-pr1",
```

**Comment by DiegoMax** [comment]
dang, i was not aware that ILIKE was not part of the sql standard :/ 
I will come later with some not so clean config option only for psql users like me. 
We could just write some sql magic to use some aggreagate functions to kind of replicate the ILIKE functionality in a db-agnostic way, however, that would mean that indices (if present) would not be used.... 
so i guess that the only way, at least for psql is to have some kind of '_usePostgresCaseInsensitiveLike_' (bool) config option.... would u be ok with that ?

**Comment by ypnos-web** [comment]
I think it would be great if CakePHP would handle the database abstraction for us. Maybe there is CakePHP functionality that we can use for the string comparison, like an expression object?
