### ISSUE TITLE
ReferenceError: dt is not defined

### ISSUE THREAD

**Issue by Gastror** [ypnos-web/cakephp-datatables#18]
Hi,

I get a ReferenceError in my browser's console when running your plugin, despite loading DataTables (normal, CakePHP and Bootstrap)

So I was wondering if there is a certain order they have to be loaded in? And, do they have to be loaded above the table element within the DOM?

**Comment by ypnos-web** [comment]
Assets need be included in the order as noted in the Quick Start Guide.
The output of `DataTables->table()` consists of a HTML and a script part. The script part depends on assets.

If you want to include assets after the table element, you can do this instead:

1. Draw the table element yourself (see https://github.com/ypnos-web/cakephp-datatables/blob/c6e7e492413262724ffafe68e1729c4c1bc514af/src/View/Helper/DataTablesHelper.php#L44-L48)
2. Obtain the script part via `$code = $this->DataTables->init($dtOptions)->draw("#{$id}");`, then do the output after loading assets, e.g. append it to Cake's script block, or wrap it in `DOMContentLoaded`, see https://developer.mozilla.org/de/docs/Web/Events/DOMContentLoaded

**Comment by Gastror** [comment]
Wouldn't running the script part at document ready be more fail-safe/efficient?

**Comment by ypnos-web** [comment]
It's hard to debug this if you don't specify which file and line these errors originate from.

It is debatable if running in document ready is better or worse. Me personally, I do it.

**Comment by Gastror** [comment]
dataTabled.bootstrap.js
cakePHP.dataTables.js

**Comment by ypnos-web** [comment]
If you already have an error in the bootstrap file, there must be something wrong with your datatables installation/include. Maybe `dataTables.js` is not the right name? The file is supposed to have a different name.

**Comment by Gastror** [comment]
They're just the files downloaded from their respective websites. I don't see how filenames matter in js files anyways,as long as theyre loaded?

**Comment by ypnos-web** [comment]
I am not in the capacity to figure out the problem you have with your dataTables installation, sure if you rename the file per-se that shouldn't matter. Any problems showing up in files of the dataTables distribution (e.g. dataTables.bootstrap.min.js) have no relation to the use of my plugin.

**Comment by Gastror** [comment]
Alright, well thank you for your fast replies and help!
