### ISSUE TITLE
Cake bake causing errors

### ISSUE THREAD

**Issue by Gastror** [ypnos-web/cakephp-datatables#19]
Hi,

I found out several operators seem to break CakePHP 3's code generation.

I got errors on:

`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/berryvan/public_html/cms/vendor/ypnos-web/cakephp-datatables/src/Controller/Component/DataTablesComponent.php on line 77
`

`
Parse error: syntax error, unexpected '?' in /home/berryvan/public_html/cms/vendor/ypnos-web/cakephp-datatables/src/Controller/Component/DataTablesComponent.php on line 94
`

`Parse error: syntax error, unexpected '?' in /home/berryvan/public_html/cms/vendor/ypnos-web/cakephp-datatables/src/Controller/Component/DataTablesComponent.php on line 193
`

I removed them and replaced them with "normal" if statements, and now everything is working as it should. Thought I'd tell you.

**Comment by ypnos** [comment]
This is PHP7 syntax. Actually we have a requirement for PHP7 in the composer.json, did you install the plugin with composer?

In any case please use the `php5` branch instead.

**Comment by ypnos-web** [comment]
This is PHP7 syntax. Actually we have a requirement for PHP7 in the composer.json, did you install the plugin with composer?

In any case please use the php5 branch instead.
