### ISSUE TITLE
Some basic config are not working ( ex : displayStart )

### ISSUE THREAD

**Issue by DeadKat** [ypnos-web/cakephp-datatables#2]
HI @ypnos-web ,

I've just checked a bit of the config options of the datatables and some simple initialization datas are not available. 

Exemple : displayStart
I've set 'displayStart' => 50, in the helper init and does not look like it's working. 

Is there any limitations there or can i use any of the configuration options from the datatables ? 

Another thing,i've made a french translation for the plugin but don't really know how to send it here, i'm quite new to git to be honest. 

Thank you for your work,

Stefan

**Comment by ypnos-web** [comment]
All DataTables options are routed through and work. However:

1. If you provide initial data as in the example in the README, it is your own responsibility that the data matches the DataTables settings.
2. If you don't want to provide initial data, don't set 'data' and 'deferLoading' in the init options. DataTables will then fetch the initial data itself (and all options are correctly recognized)

**Comment by ypnos-web** [comment]
Are you still having problems with configuration options?

**Comment by DeadKat** [comment]
Hi @ypnos-web ,

yes it looks like everything is working, i wasn't using the correct option ( the one to display 50 records by default). 

Sorry i did not made this report as closed. 

Thank you again for your work and advices. 

Stefan.

**Comment by DeadKat** [comment]
Hi @ypnos-web,

i have checked the lengthMenu option and i can't get it to work, can you please tell me if it's supported ? 

https://datatables.net/reference/option/lengthMenu

this is what's in my init call : 

`"pageLength" => 50,
"lengthMenu" =>  [[10, 25, 50, -1],[10, 25, 50, __('All')] ],`

Thank you,

Stefan.

**Comment by ypnos-web** [comment]
Hello, this is because we have a custom language.lengthMenu option as a default. I might remove that, it stems from the original code.

Have a look at: https://datatables.net/reference/option/language.lengthMenu
Basically you just need to set sth. like this: 'language' => ['lengthMenu' => 'Show _MENU_ entries']

**Comment by DeadKat** [comment]
Hello @ypnos-web,

i think we misunderstood each others, i was not referencing to a translation (though I understand what you're poiting at), I'm referencing the option itself this example is also not working in my case : 

`"lengthMenu" => [10, 25, 50, 100 , 200 , 300]`

what i want is to have for example an option in the dropdown which could list 500 records , it might sound weird but the project i'm working on includes a lot of records. 

This example from the datatables options page is not working either (this is what i took as a basis) : 

`$('#example').dataTable( {
  "lengthMenu": [ 10, 25, 50, 75, 100 ]
} );`

Thank you again for your time.

Stefan.

**Comment by ypnos-web** [comment]
Have a look at the second example in the datatables documentation that I linked. This is what the plugin is by default doing right now. That is why you have to change this option as I suggested to make your other option work.

**Comment by DeadKat** [comment]
Woops my bad, just had a quick look, trying this right now. 

Thank you. 

Stefan.
