### ISSUE TITLE
Columns "actions"

### ISSUE THREAD

**Issue by ranferi** [ypnos-web/cakephp-datatables#21]
Is there a way to put a column "actions" like this

```
<td class="actions">
    <?= $this->Html->link(__('View'), ['action' => 'view', $User->id]) ?>
</td>
```

?

**Comment by ypnos-web** [comment]
Very easy to do with callback functions. See https://github.com/ypnos-web/cakephp-datatables/wiki/Callback-functions

See also https://github.com/ypnos-web/cakephp-datatables/blob/master/webroot/js/cakephp.dataTables.js#L96

**Comment by ranferi** [comment]
Thanks ypnos!! I will check them out
