### ISSUE TITLE
Draw callbacks

### ISSUE THREAD

**Issue by Gastror** [ypnos-web/cakephp-datatables#24]
Hi,

I'm sorry I seem to have some trouble understanding how to attach a callback to the draw event.
I've tried numerous things none of which seem to work.

Could you maybe provide an example? If you have other things to do, don't mind this. I'm still relatively new to coding and I just seem not to get how to get this to work, as I'm sure it is just an amateur's mistake.

My code right now is:

> <?php
> $options = [
>   'ajax' => [
>       'url' => $url // current controller, action, params
>   ],
>   'language' => [
>       'url' => 'http://cdn.datatables.net/plug-ins/1.10.12/i18n/Dutch.json'
>   ],
>   'Callbacks' => [
>       'drawCallback' => 'dt.render.drawn'
>   ],
>   'data' => $data,
>   'deferLoading' => $recordsTotal,
>   'columns' => [
>       [
>           'name' => 'Posts.id',
>           'data' => 'id',
>           'visible' => true,
>           'searchable' => false,
>       ],
>       [
>           'title' => __('Name'),
>           'name' => 'Posts.name',
>           'data' => 'name',
>       ],
>       [
>           'title' => __('Tags'),
>           'name' => 'Posts.tags',
>           'data' => 'tags'
>       ],
>       [
>           'title' => __('Publish date'),
>           'name' => 'Posts.date',
>           'data' => 'date'
>       ],
>       [
>           'title' => __('Removal date'),
>           'name' => 'Posts.end_date',
>           'data' => 'end_date'
>       ],
>   ],
>   'order' => [3, 'asc'], // order by date
> ];
> ?>
> 
> <?= $this->DataTables->table('posts-table', $options, ['class' => 'table table-striped']); ?>

**Comment by ypnos-web** [comment]
It is explained in the wiki: https://github.com/ypnos-web/cakephp-datatables/wiki/Callback-functions
You cannot pass a javascript function object as a string. That is why you need to use the callback wrapper, e.g.
`'render' => $this->DataTables->callback('dt.render.date'),`

**Comment by Gastror** [comment]
Alright, thank you. Where, in the options array, would I bind an alert to for example draw.dt ?
