### ISSUE TITLE
Possible to load external data in a datatable?

### ISSUE THREAD

**Issue by lorro** [ypnos-web/cakephp-datatables#25]
Hi,

I'm actually trying to do the following. I acknowledge this is not normal behavior of the plugin ;)
I have some data that I would like to render in the datatable. Problem is: this data doesn't come from my own database but is some data that I got via JSON from an external url.

I created a custom finder method to do this, and let the find wrapper of DataTables fetch this. Problem is this isn't a query object (instead it's an array of entities at the moment) so it can't execute ->count &  ->limit calls. So for the moment I'm not getting there :-)

Do you think what I'm trying to do is in any way possible? 

Thanks

**Comment by ypnos-web** [comment]
The first question is, do you plan to use filter, offset and limit functionality? If not, as I see it, only `count()` and `order()` are called.

You could write a class, even an anonymous one, that wraps your array and provides these calls. It can also provide a `toArray()` method that would probably be called during serialization.

A more general solution would be to implement the [QueryInterface](http://api.cakephp.org/3.3/class-Cake.Datasource.QueryInterface.html).

If you don't like that approach, you could also patch the DataTablesComponent `find()` method. I believe that's all the code you would need to touch.

**Comment by lorro** [comment]
Thanks for quick reply!

Yes, I would like to be able to filter/paginate that datatable. For now I've just created a simple datatable that only filters/paginated on the frontend (no backend func), but that could slow the site when the data gets bigger and bigger :)

So I would have to create a class that implements that interface you mentioned and that takes in the data array?

What do you mean exactly with patch the find() method? I guess you don't mean change code in your plugin files? :) Or do I just need to provide my own version of that find method somewhere in the app. In a trait or so?

Thanks

**Comment by ypnos-web** [comment]
Sorry Lorro, I totally missed out on your follow-up questions. Were you able to solve your problem?

**Comment by lorro** [comment]
I ended up with another solution. The external url was also my property (just 2 systems of us that needed to communicate with each other) so I was able to just write a sort of API function that returned me the data in json format. So I could use it in the datatable.

**Comment by ypnos-web** [comment]
Great to hear you found a solution!
