### ISSUE TITLE
override length/limit value

### ISSUE THREAD

**Issue by emnu** [ypnos-web/cakephp-datatables#28]
is there any way i can override length/limit value in 

    protected $_defaultConfig = [
        'start' => 0,
        'length' => 10, // <-- THIS VALUE
        'order' => [],
        'prefixSearch' => true, // use "LIKE …%" instead of "LIKE %…%" conditions
        'conditionsOr' => [],  // table-wide search conditions
        'conditionsAnd' => [], // column search conditions
        'matching' => [],      // column search conditions for foreign tables
    ];

**Comment by ypnos-web** [comment]
Yes. This is standard component config handling. See http://book.cakephp.org/3.0/en/controllers/components.html#configuring-components

**Comment by emnu** [comment]
thank you for your response, can it being override on the fly? such as

        $data = $this->DataTables->find('Menus', 'threaded', [
            'length' => 100,
        ]);

**Comment by ypnos-web** [comment]
Sorry for not replying earlier, I was sick. Good to know you could resolve your question!
