### ISSUE TITLE
 The requested package could not be found in any version 

### ISSUE THREAD

**Issue by incredibleX** [ypnos-web/cakephp-datatables#3]
I just added the following line to my composer.json:
`"require": {
    "ypnos-web/cakephp-datatables": "dev-master"
}`

executed composer update and i'm getting this error:

> 
> C:\xampp\htdocs\cake>composer update
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package ypnos-web/cakephp-datatables could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> 

Am I doing anything wrong?

**Comment by ypnos-web** [comment]
The repository is not registered so you have to add it to your composer.json as explained here:
https://getcomposer.org/doc/05-repositories.md#using-private-repositories

**Comment by ypnos-web** [comment]
I also published on packagist now, so it should work without adding the custom VCS entry.
