### ISSUE TITLE
Bug on columns when multiple DataTables on same page

### ISSUE THREAD

**Issue by Wgr18** [ypnos-web/cakephp-datatables#32]
Hello, 

I've noticed a small problem with your plugin.
When there is more than one table on a page and a table has more columns than another following table, the following table retrieves the column from the preceding table.

For example:
DataTable 1
|Column 1|Column 2|Column 3|
3 columns are defined in PHP.

DataTable 2
|Column 1|Column 2|
2 columns are defined in PHP.

DataTable 1 is defined before DataTable 2 on the page 

Will output:

DataTable 1
|Column 1|Column 2|Column 3|

DataTable 2
|Column 1|Column 2|Column 3|

Here is an example with actual code:

```
<script>
	function dummydata(){
		return "test";
	}
</script>

<?php
	$options = [
		'ajax' => [
			'url' => '/stats/testjson.json'
		],
		'columns' => [
			[
				'orderable' => false,
				'data' => null,
				'searchable' => false,
				'title' => "Column dt 1-1",
				'render' => $this->DataTables->callback('dummydata'),
			],
			[
				'orderable' => false,
				'data' => null,
				'searchable' => false,
				'title' => "Column dt 1-2",
				'render' => $this->DataTables->callback('dummydata'),
			]
		],
		'infos' => false,
		'oLanguage' => [
			'sLengthMenu' => __('Display').' _MENU_ '.__('per page'),
			'sSearch' => '<span class="fa fa-search"></span>',
			'sSearchPlaceholder' => __('Search...'),
			'sZeroRecords' => __('No data available')
		],
	];

	echo $this->DataTables->table('dt1', $options, ['class' => 'array striped link']);
?>

<?php
	$options = [
		'ajax' => [
			'url' => '/stats/testjson.json'
		],
		'columns' => [
			[
				'orderable' => false,
				'data' => null,
				'searchable' => false,
				'title' => "Column dt 2-1",
				'render' => $this->DataTables->callback('dummydata'),
			],
		],
		'infos' => false,
		'oLanguage' => [
			'sLengthMenu' => __('Display').' _MENU_ '.__('per page'),
			'sSearch' => '<span class="fa fa-search"></span>',
			'sSearchPlaceholder' => __('Search...'),
			'sZeroRecords' => __('No data available')
		],
		'responsive' => false
	];

	echo $this->DataTables->table('dt2', $options, ['class' => 'array striped link']);
?>

```
Give this:
![dt1](https://cloud.githubusercontent.com/assets/22372440/23793922/eb79cc34-058d-11e7-94c1-232fa05fa165.png)

I've search a solution and find out that this 3 lines solves the problem:

```
        $this->_configDelete('data');
        $this->_configDelete('deferLoading');
        $this->_configDelete('columns');
```

in file /cakephp-datatables/src/View/Helper/DataTablesHelper.php in function init line 57.

```
public function init(array $options = [])
{
        //new line here
        $this->_configDelete('data');
        $this->_configDelete('deferLoading');
        $this->_configDelete('columns');

       // -- load i18n (defaults from datatables.net/reference/option/language)
       $this->config('language', [
       //rest of code
      ...
}

```

Now it output this:

![dt2](https://cloud.githubusercontent.com/assets/22372440/23794153/054385e6-058f-11e7-8fda-42792cc39f81.png)

Can you look at my changes in case I missed something ?

**Comment by ypnos-web** [comment]
Thank you for the report, I see the problem and your solution, and will have a further look.

**Comment by Wgr18** [comment]
Great!
Are you planning to update the plugin?

**Comment by ypnos-web** [comment]
Yes, a fix is already underway.
