### ISSUE TITLE
How to view/edit/delete options to each record?

### ISSUE THREAD

**Issue by ullas** [ypnos-web/cakephp-datatables#35]
I am trying to use edit/delete/view buttons to all the rows. How Can I achieve this?

**Comment by ypnos-web** [comment]
The typical approach to this is to have a dedicated column for the buttons. You can tell DataTables to call a javascript function for rendering a column. Your Javascript function can then render the buttons.

See the documentation at https://github.com/ypnos-web/cakephp-datatables/wiki/Callback-functions

As you can see there, you can also pass extra arguments from PHP to the callback function. That allows you to pass e.g. any markup/style options or the targets of the buttons. E.g. from the view:

```php
columns => [
    [
        'searchable' => false,
        'sortable' => false,
        'name' => 'Users.id',
        'data' => 'id',
        'render' => $this->DataTables->callback('buttonRenderer',
            [$this->Url->build('action' => 'view'), $this->Url->build('action' => 'edit')]),
    ],
    …
```

Then the javascript function `buttonRenderer` can append the id to the respective URL for each button.

Also have a look at this function:
https://github.com/ypnos-web/cakephp-datatables/blob/master/webroot/js/cakephp.dataTables.js#L88-L109

You can use it with the DataTables select plugin to make rows selectable (e.g. to trigger a visit to the view action).

**Comment by ullas** [comment]
Thanks... It works!!!
