### ISSUE TITLE
Set default number of entries?

### ISSUE THREAD

**Issue by ThomasNucleus** [ypnos-web/cakephp-datatables#36]
For options, I have tried specifying the following

        'pageLength' => 100,
        'iDisplayLength' => 100,

At the top of the page, it does have 100 selected. At the bottom it also says "Showing 1 to 100 of 108 entries"

However on the page it still only shows 10 records. Only when I change between the pages does it display 100 entries on a page. Is there another way I should be setting the default number of entries that are displayed?

**Comment by ypnos-web** [comment]
There is two scenarios here:

- DataTables requests data from the server via AJAX. DataTables sets offset and limit in the request
- The data is supplied when rendering the page. You have to ensure that offset and limit match the datatables configuration

Now how to ensure that in the second case? Have a look at the `DatatablesComponent` configuration:

```php
protected $_defaultConfig = [
        'start' => 0,
        'length' => 10,
        'order' => [],
        'prefixSearch' => true, // use "LIKE …%" instead of "LIKE %…%" conditions
        'conditionsOr' => [],  // table-wide search conditions
        'conditionsAnd' => [], // column search conditions
        'matching' => [],      // column search conditions for foreign tables
        'comparison' => [], // per-column comparison definition
    ];
```
So in your example, you would have to set the length option of the component according to your page length.
