### ISSUE TITLE
Filtering for a decimal field

### ISSUE THREAD

**Issue by frent** [ypnos-web/cakephp-datatables#39]
HI there, I was wondering if was possible to do a search/filter for a decimal field (as in an amount/total).
Currently for each of my fields it creates a LIKE '%value% but for my decimal field it puts '0.000000' in the actual SQL query. This because the type of that field is decimal.

I read that you can cast the decimal to string on query https://github.com/cakephp/cakephp/issues/6470
But don't know if you have a solution already in place

**Comment by ypnos-web** [comment]
First of all, if you switch to the `devel` branch, the comparison used should be more appropriate for the decimal type (but this is configurable).

However as I understood it, you want a string comparison and you want the input (coming from datatables) to be formatted in a specific way?

I don't understand what you mean by
> but for my decimal field it puts '0.000000' in the actual SQL query

Could you give an example?

**Comment by lorro** [comment]
Hi,

Jumping in here, I've got the exact same issue.
I'm not able to switch to devel branch, hence I'm using php5.

I want to filter a datatable by an order total (= decimal). When I fill f.e. the value 48 in datatable search field, cakePHP creates the following where condition.
```SQL
WHERE 
  (
    (
      Invoices.nr like '%48%' 
      OR Orders.nr like '%48%' 
      OR Invoices.payment_last_name like '%48%' 
      OR Invoices.shipping_last_name like '%48%' 
      OR Invoices.payment_phone like '%48%' 
      OR Orders.total_incl_vat like '0.000000' 
      OR Invoices.total_incl_vat like '0.000000'
    ) 
  )
```

Or is there a way to tell your plugin to treat that column as a string perhaps?

Thanks

**Comment by ypnos-web** [comment]
The plugin does not mangle with column types. This comes [from CakePHP itself](https://github.com/cakephp/cakephp/issues/6470) as was noted above.

One solution is to use the `delegateSearch` option to the `find()` method. Then, in your finder (InvoicesTable), read the `globalSearch` option that will contain the search string. Write your own WHERE clauses there and provide the type option (again, [see here](https://github.com/cakephp/cakephp/issues/6470)).
