### ISSUE TITLE
Working with contains and linked data

### ISSUE THREAD

**Issue by DeadKat** [ypnos-web/cakephp-datatables#4]
Hi @ypnos-web ,

I have a small issue today. 

I'm displaying a datatable of users, users can be linked to an organization or not. 
In my datatable i'm showingt user data and the organization name but i have an error if a user is not linked to an organization. 

Here is the JSON reponse from the request : 

`{
	"recordsTotal": 2,
	"recordsFiltered": 2,
	"draw": 1,
	"data": [{
		"id": "c56a3d41-a95c-4f6b-beda-a2c2bf04ca19",
		"email": "email@domain2.com",
		"password": "$2y$10$tLy7hgjMI1dIXATE3yoNs.p0b995VvzrfmVfwEqwhaAvm2AQl52AG",
		"lang": "fr",
		"droit": "admin",
		"organization_id": "bb3dfa8e-c093-481b-8aba-0ab6ab93e154",
		"structure_id": "d1707263-13f5-4836-8a8b-e4a2d44a0764",
		"deleted": null,
		"nom": "Cr\u00e9ation",
		"prenom": "Altitude",
		"modified": "2016-04-01T10:39:32+0000",
		"valid": true,
		"organization": {
			"id": "bb3dfa8e-c093-481b-8aba-0ab6ab93e154",
			"name": "Altitude Cr\u00e9ation",
			"deleted": null,
			"modified": "2016-03-30T13:57:09+0000",
			"_locale": "fr"
		},
		"structure": {
			"id": "d1707263-13f5-4836-8a8b-e4a2d44a0764",
			"name": "Observatoire des Mamif\u00e8res Marins",
			"color": "#405581",
			"logo": null,
			"polygonne": null,
			"zone_id": null,
			"url": "http:\/\/obs-mam.org",
			"deleted": null,
			"description": "\u003Cp\u003EL\u0026rsquo;Observatoire des mammif\u0026egrave;res marins, ou OBS MAM, est un r\u0026eacute;seau compos\u0026eacute; d\u0026rsquo;institutions et d\u0026rsquo;associations activement impliqu\u0026eacute;es dans la pr\u0026eacute;servation de l\u0026rsquo;environnement et de la faune sauvage. Ce r\u0026eacute;seau centralise toutes les observations de mammif\u0026egrave;res marins qui lui sont transmises, afin d\u0026rsquo;envisager des programmes de pr\u0026eacute;servation.\u003C\/p\u003E",
			"acronym": "",
			"modified": "2016-03-25T14:55:31+0000",
			"_locale": "fr"
		}
	}, {
		"id": "bf1c72b6-fd3d-4eeb-b63e-a127c212dd79",
		"email": "email@domain.com",
		"password": "$2y$10$HF1sYc7b90EFWduSYz6PF.D36II.Z51iGOC28CrKd73q2By0ZIJr6",
		"lang": "fr",
		"droit": null,
		"organization_id": null,
		"structure_id": "d1707263-13f5-4836-8a8b-e4a2d44a0764",
		"deleted": null,
		"nom": "KRUGER",
		"prenom": "stefan",
		"modified": "2016-04-01T12:33:12+0000",
		"valid": true,
		"organization": null,
		"structure": {
			"id": "d1707263-13f5-4836-8a8b-e4a2d44a0764",
			"name": "Observatoire des Mamif\u00e8res Marins",
			"color": "#405581",
			"logo": null,
			"polygonne": null,
			"zone_id": null,
			"url": "http:\/\/obs-mam.org",
			"deleted": null,
			"description": "\u003Cp\u003EL\u0026rsquo;Observatoire des mammif\u0026egrave;res marins, ou OBS MAM, est un r\u0026eacute;seau compos\u0026eacute; d\u0026rsquo;institutions et d\u0026rsquo;associations activement impliqu\u0026eacute;es dans la pr\u0026eacute;servation de l\u0026rsquo;environnement et de la faune sauvage. Ce r\u0026eacute;seau centralise toutes les observations de mammif\u0026egrave;res marins qui lui sont transmises, afin d\u0026rsquo;envisager des programmes de pr\u0026eacute;servation.\u003C\/p\u003E",
			"acronym": "",
			"modified": "2016-03-25T14:55:31+0000",
			"_locale": "fr"
		}
	}]
}`

The field i'm display is organization.name but in the case a user is not linked to any the object is null which is logical. 

The problem is datatable don't have anything to work with in the organization i think. 

Is there any workaround for this ?

Thank you,

Stefan.

**Comment by ypnos-web** [comment]
You can solve the problem of missing data in at least two ways:

1. Server-side: 
 - Overwrite your Entity classe's `toArray()` to inject an empty string, e.g.
```php
   public function toArray()
   {
       $ret = parent::toArray();
       if (!isset($ret['organization'])) {
           $ret['organization'] = ['name' => ''];
       }
       return $ret;
   }
```

2. Client-side:
 - Create a custom render callback. JS code:
```js
function renderOptional(data, type, full, meta, limit)
{
    if (typeof(data) === 'undefined')
        return '';
    return data;
}
```
  - Set the callback in your config:
```php
            [
                'title' => __('Organization'),
                'name' => 'Organizations.name',
                'data' => 'organization.name',
                'render' => $this->DataTables->callback('renderOptional')
            ],
```

**Comment by DeadKat** [comment]
Working on first try ! Big Thanks :)
