### ISSUE TITLE
Cake 3.6 compatibility 

### ISSUE THREAD

**Issue by cewi** [ypnos-web/cakephp-datatables#49]
In the DataTablesHelper's initialize-Method, 
`$this->config('language')` should be changed to `$this->getConfig('language')` and
`$this->config('language', [ ...` to `$this->setConfig('language', [ ...`
Don't know if other changes might be necessary.
BTW: Thank you for your work!

**Comment by ypnos-web** [comment]
Yes, I am aware of the deprecations. I did not change anything yet to stay backwards compatible.

My plan of action is to introduce a release system, make the current `devel` branch a release 2.0 and at the same time remove use of methods deprecated in 3.5.

**Comment by ypnos-web** [comment]
Fixed in 6aac55c3bbbf4a5dd6ae58868a512cfb260deb07
