### ISSUE TITLE
v2.0 incompatible with Cake v3.3 because of use of `Cake\ORM\Table::getConnection()`

### ISSUE THREAD

**Issue by florentpoujol** [ypnos-web/cakephp-datatables#51]
Hello and thanks for this lib, which we make a good use of at my company.

We still use CakePHP v3.3, so I am updating to you v2.0, however, line 296 of `DataTablesComponent` throws an exception, because you use `Cake\ORM\Table::getConnection()`, which was only introduced in Cake v3.4...  
Line 296 is just this one : `if ($this->_table->getConnection()->getDriver() instanceof Postgres) {`

For now I just commented this piece of code since we don't use Postgres, but should we switch v1.0 instead or do you consider this a bug on your end that you will fix ?

Thanks for your time !

**Comment by florentpoujol** [comment]
It does work. :D

From their documentation, `Cake\ORM\Table::connection()` and `Cake\Database\Connection::driver()` exists since Cake v3.0.

I will do the PR later, but today.

**Comment by ypnos-web** [comment]
Fixed in 221f478
