### ISSUE TITLE
Uncaught ReferenceError: dt is not defined

### ISSUE THREAD

**Issue by renjithjr** [ypnos-web/cakephp-datatables#59]
Notice (8): Undefined index: columns [ROOT/vendor/ypnos-web/cakephp-datatables/src/View/Helper/DataTablesHelper.php, line 101]

Warning (2): Invalid argument supplied for foreach() [ROOT/vendor/ypnos-web/cakephp-datatables/src/View/Helper/DataTablesHelper.php, line 101]

**Comment by ypnos-web** [comment]
Seems like you forgot to provide `columns` option as explained in the tutorial.

**Comment by renjithjr** [comment]
No i have provided columns option as explained in the tutorial.

$columns = [
            [
                'field' => 'Customers.id',
                'data' => 'id',
                'searchable' => false,
            ],            
            [
                'title' => __('Title'),
                'field' => 'Customers.name',
                'data' => 'name'
            ],
            [
                'title' => __('Actions'),
                'field' => 'Customers.id',
                'data' => 'id'
            ],
        ];

**Comment by ypnos-web** [comment]
Please provide full code, this snippet does not show your call into DataTables helper.

**Comment by renjithjr** [comment]
<script type="text/javascript">    
    <?php    
    $options = [
        'ajax' => [
        'url' => $this->Url->build() // current controller, action, params
    ],
    'data' => $data,
    'deferLoading' => $data->count(), // https://datatables.net/reference/option/deferLoading
    'columns' => [
		[
			'data' => 'id',
			'visible' => false,
			'searchable' => false,
		],
		[
			'title' => __(' Name'),
			'data' => 'name'
		],
	],
    ];
    echo $this->DataTables->draw('dataTable', $options, ['class' => 'table table-striped']);
    ?>
    
    $(document).ready(function() {
		DATATABLE = $('#dataTable').dataTable();
		});
</script>




public function index()
    {
        $columns = [
            [
                'field' => 'Customers.id',
                'data' => 'id',
                'searchable' => false,
            ],            
            [
                'title' => __('Title'),
                'field' => 'Customers.name',
                'data' => 'name'
            ],
            [
                'title' => __('Actions'),
                'field' => 'Customers.id',
                'data' => 'id'
            ],
        ];

        $data = $this->DataTables->find('Customers', 'all', ['conditions'=>[], 'order'=>'Customers.id desc'], $columns);

        $this->set('columns', $columns);
        $this->set('data', $data);
        $this->set('_serialize', array_merge($this->viewVars['_serialize'], ['data']));
    }

**Comment by ypnos-web** [comment]
Please format your code in a readable manner, to be honest I consider it quite rude to dump the code like this when you are asking for help.

**Comment by renjithjr** [comment]
<script type="text/javascript">    
    <?php    
    $options = [
        'ajax' => [
        'url' => $this->Url->build() // current controller, action, params
    ],
    'data' => $data,
    'deferLoading' => $data->count(), // https://datatables.net/reference/option/deferLoading
    'columns' => [
		[
			'data' => 'id',
			'visible' => false,
			'searchable' => false,
		],
		[
			'title' => __(' Name'),
			'data' => 'name'
		],
	],
    ];
    echo $this->DataTables->draw('dataTable', $options, ['class' => 'table table-striped']);
    ?>
    
    $(document).ready(function() {
		DATATABLE = $('#dataTable').dataTable();
		});
</script>

**Comment by renjithjr** [comment]
<script type="text/javascript">    
    <?php    
    $options = [
        'ajax' => [
        'url' => $this->Url->build() // current controller, action, params
    ],
    'data' => $data,
    'deferLoading' => $data->count(), // https://datatables.net/reference/option/deferLoading
    'columns' => [
		[
			'data' => 'id',
			'visible' => false,
			'searchable' => false,
		],
		[
			'title' => __(' Name'),
			'data' => 'name'
		],
	],
    ];
    echo $this->DataTables->draw('dataTable', $options, ['class' => 'table table-striped']);
    ?>
    
    $(document).ready(function() {
		DATATABLE = $('#dataTable').dataTable();
		});     
</script>

**Comment by renjithjr** [comment]
![screen shot 2018-07-02 at 4 33 55 pm](https://user-images.githubusercontent.com/20161509/42160678-bfd414b6-7e15-11e8-9d75-495404ca8f26.png)

**Comment by renjithjr** [comment]
![screen shot 2018-07-02 at 4 34 53 pm](https://user-images.githubusercontent.com/20161509/42160712-e08de254-7e15-11e8-9623-2ef1d9559341.png)

**Comment by ypnos-web** [comment]
Next time try ```php it is in the Github Markdown documentation.

**Comment by ypnos-web** [comment]
There is some other problems in your code, but I really don't see how you could get to this error message with the code you posted.

1. use $columns passed from controller instead of re-defining
2. selector argument to draw() is missing a '#'
3. what's the document.ready event handler supposed to do?

**Comment by renjithjr** [comment]
public $columns=["tablename.id","tablename.suffix"] ;
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $data = $this->DataTables->find('tablename', 'all', [
             'order' => ['tablename.suffix' => 'asc']
        ]);

        $this->set('data', $data);
		$this->set('_serialize', array_merge($this->viewVars['_serialize'], ['data']));
		

    }

**Comment by renjithjr** [comment]
$options = [
'ajax' => [
'url' => $this->Url->build() // current controller, action, params
],
//'ajax'=>$this->DataTables->callback('dt.lcCache',[$this->Url->build()]),
'data' => $data,
"deferRender"=> true,
'colReorder'=> true,
'saveState' => true,
'responsive'=> true,

'dom'=> "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
'buttons'=> [
['extend'=> 'copy','className'=> 'btn-sm'],
['extend' => 'csv','title'=> $name.'List', 'className'=> 'btn-sm'],
['extend' => 'pdf', 'title'=> $name. 'List', 'mColumns'=> 'visible','className'=> 'btn-sm'],
['extend' =>'print','className'=> 'btn-sm'],
['extend'=> 'colvis','text'=>'Columns','className'=> 'btn-sm','columns'=>':not(.noVis)'] ,
[
'text'=> 'Add',
'className'=> 'btn-sm btnAdd'
]

],
//'deferLoading' => $data->count(), // https://datatables.net/reference/option/deferLoading
'columns' => $columns,
'order' => [1, 'asc'],
'rowCallback' => $this->DataTables->callback('dt.render.rowCallBack'),
'drawCallback' => $this->DataTables->callback('dt.render.drawCallback')
];

**Comment by renjithjr** [comment]
Getting Error as "Uncaught ReferenceError: dt is not defined" in console and on click it shows as below : 
 
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65</pre></div></pre><table id="tablename-table" class="dataTable "></table><script>dt.initDataTables('#tablename-table', {"class":"table table-striped table-hover","searching":true,"processing":true,"serverSide":true,"deferRender":true,"className":"DataTables.DataTables","language":{"emptyTable":"No data available in table","info":"Showing _START_ to _END_ of _TOTAL_ entries","infoEmpty":"No entries to show","infoFiltered":"(filtered from _MAX_ total entries)","lengthMenu":"Show _MENU_ entries","processing":"Processing...","search":"Search:","zeroRecords":"No matching records found","paginate":{"first":"First","last":"Last","next":"Next","previous":"Previous"},"aria":{"sortAscending":": activate to sort column ascending","sortDescending":": activate to sort column descending"}}});
