### ISSUE TITLE
Column ordering requested, but no column definitions provided.

### ISSUE THREAD

**Issue by renjithjr** [ypnos-web/cakephp-datatables#60]
Generating column values on the view and not from the controller,produces the above mentioned error.

Is it not possible to assign column values from the view and not on the controller?

**Comment by ypnos-web** [comment]
If you want a table that is operated client-side only, you do not need column definitions in controller. However if your table uses server-side processing the controller needs to know. It is a security measure.

Have a look at [my comment here][1] on how this can be done in an elegant way, and you only have to define few of the colum properties in the controller.

[1]: https://github.com/ypnos-web/cakephp-datatables/issues/43#issuecomment-395736360
