### ISSUE TITLE
Concatenate / Modify row result

### ISSUE THREAD

**Issue by renjithjr** [ypnos-web/cakephp-datatables#64]
Is it possible to concatenate two/more row values from database and display it in single row of datatable?

**Comment by ypnos-web** [comment]
You can do this on the client side through datatables, e.g. https://datatables.net/forums/discussion/33000/how-to-concat-two-or-more-columns-of-same-datatabase-table-to-show-in-a-single-datatable-column

You could also do something like this in the ORM Table's finder.
