### ISSUE TITLE
Display linked table count in one column

### ISSUE THREAD

**Issue by renjithjr** [ypnos-web/cakephp-datatables#68]
Is it possible ?

**Comment by ypnos-web** [comment]
In your finder you can create that column for the query output and then just display as usual.
However, the way I do it is that I use CounterCache behavior: https://book.cakephp.org/3.0/en/orm/behaviors/counter-cache.html

**Comment by renjithjr** [comment]
Concatenate two or more columns into single column ?

**Comment by ypnos-web** [comment]
Write a render callback for that. See https://github.com/ypnos-web/cakephp-datatables/blob/master/webroot/js/cakephp.dataTables.js#L202 for an example. Use `full` parameter to access other columns' values.
