### ISSUE TITLE
Use callback functions on DataTables->init [from source project]

### ISSUE THREAD

**Issue by DeadKat** [ypnos-web/cakephp-datatables#7]
Hi @ypnos-web ,

I've taken this question from the base project @fheider . 

I've folloowed what you've written up there because i have the exact functionnality discribed : drawing a small block with a color to display rather than the css hexa code. 

`[
			'title' => __('Color'),
			'name' => 'Structures.color',
			'data' => 'color',
			'render' => 'callback:renderColor',
		],` 

Here is the line describing the column. Is there something wrong in there ? 

Thank you again for your time. 

Stefan.

**Comment by ypnos-web** [comment]
The new API still needs to be documented, but in the new API you would do

```php
'render' => $this->DataTables->callback('renderColor')
```

**Comment by DeadKat** [comment]
Worked like a charm, thank you again for your time and advices :) :+1:
