### ISSUE TITLE
Like Operator on Search

### ISSUE THREAD

**Issue by spacebiscuit** [ypnos-web/cakephp-datatables#71]
I have noticed that the global search for each table seems to work on right side LIKE operator meaning that it will only match the beginning of any row data.

Is it possible to use left and right side LIKE operator so that if my table row data is "this is a string", "string" would be matched where as currently it isn't.

Thanks

**Comment by ypnos-web** [comment]
Use the `prefixSearch` option of the component for this:
https://github.com/ypnos-web/cakephp-datatables/blob/master/src/Controller/Component/DataTablesComponent.php#L25

**Comment by ypnos-web** [comment]
Sorry, I thought your question was already resolved. This is an option of the component right now. So you can set it with `setConfig()` or in the component initialization (refer to CakePHP manual).

**Comment by spacebiscuit** [comment]
Perfect thank you it work :)
