### ISSUE TITLE
Filter table with integer 0

### ISSUE THREAD

**Issue by treyphax** [ypnos-web/cakephp-datatables#72]
I had troubles filtering my table using a integer value of 0, as my table would get filtered with "null" instead of "0".
The issue seems to come from line 184 of DataTablesComponent.php, since empty() returns true for not only "null", but also for "0" as an integer.

The issue has been resolved by replacing
`!empty($localSearch)`
with
`!empty($localSearch) || $localSearch === '0'`

**Comment by ypnos-web** [comment]
Thank you for your report. I will fix this.

**Comment by ypnos-web** [comment]
Please let me know if the fix works for you.

**Comment by treyphax** [comment]
It works, thanks.
