### ISSUE TITLE
Search for "0" - Zero value 

### ISSUE THREAD

**Issue by frent** [ypnos-web/cakephp-datatables#77]
When searching for a number (zero) for localSearch, you don't get into the localsearch cause of empty check. 

It can be fixed for also checking on the length according to the stackoverflow question: https://stackoverflow.com/questions/410002/fixing-the-php-empty-function

Line: 184
`if (!empty($localSearch) || strlen($localSearch) != 0) {`

**Comment by ypnos-web** [comment]
I don't understand. [Line 184](https://github.com/ypnos-web/cakephp-datatables/blob/8e2f7d841535505c86d05be13cef392542f399c3/src/Controller/Component/DataTablesComponent.php#L184):

`if ($localSearch !== '') {`

Why would that check fail for "0" or 0?

**Comment by ypnos-web** [comment]
Did you miss this commit? https://github.com/ypnos-web/cakephp-datatables/commit/8e2f7d841535505c86d05be13cef392542f399c3

**Comment by frent** [comment]
Sorry my mistake! I guess it didn't update.
