### ISSUE TITLE
Failed calling Cake\ORM\Query::jsonSerialize() 

### ISSUE THREAD

**Issue by dividedbynothing** [ypnos-web/cakephp-datatables#9]
Hi, thanks a lot for getting this going!

I've got the following error when I load my index.ctp:

> Failed calling Cake\ORM\Query::jsonSerialize() 

The error first points to line 88 of DataTablesHelper.php, then to line 50.

My App controller should be OK; it's per the guide.

For my assets, I have added them at the top of my index.ctp as follows:
```
$this->Html->script([
    'jquery-2.2.0.min.js',
    'jquery.dataTables.min.js',
    'dataTables.bootstrap.min.js',
    'DataTables.cakephp.dataTables.js',
], ['block' => true]);

$this->Html->css('dataTables.bootstrap.css', ['block' => true]);
```

Note, I've put the files in my webroot js and css directories.

My Controller looks like this:
`     $data = $this->DataTables->find('Items', 'all', [
       'order' => ['username' => 'asc']
]);
$this->set('data', $data);
$this->set('_serialize', array_merge($this->viewVars['_serialize'], ['data']));
}`

And in my index.ctp:

```
$options = [
    'ajax' => [
        'url' => $this->Url->build() // current controller, action, params
    ],
    'data' => $data,
    'deferLoading' => $data->count(), // https://datatables.net/reference/option/deferLoading
    'columns' => [
        [
            'name' => 'Items.id',
            'data' => 'id',
            'visible' => false,
            'searchable' => false,
        ],
        [
            'title' => __('Item Number'),
            'name' => 'Items.item_number',
            'data' => 'item_number'
        ],
        [
            'title' => __('Description'),
            'name' => 'Items.description',
            'data' => 'description'
        ],
        [
            'title' => __('Type'),
            'name' => 'Items.type',
            'data' => 'type',
            'className' => 'text-primary',
        ],
    ],
    'order' => [2, 'asc'], // order by username
];

echo $this->DataTables->table('items-table', $options, ['class' => 'table table-striped']);
```

Not sure what's going on here.... if you have any advice, that would be great!
Thanks again for your work on this project.
DBN

**Comment by dividedbynothing** [comment]
Just an additional note on this....
If I comment out the
`echo $this->DataTables->table('items-table', $options, ['class' => 'table table-striped']);`
from my index.ctp, the error does not occur.
But obviously nothing is displayed in the body of the page after the default header.

**Comment by ypnos-web** [comment]
The error occurs when `$data` is JSON-encoded to be sent to the client in JSON format.

Internally, this calls `jsonSerialize()` on the Query object (which would then use `toArray()`). So this is the point when the query is executed and data is read.

I had this error many times and it was always caused by a problem in my model. The most prominent cause for this error is a faulty SQL statement.

Unfortunately it is quite cumbersome to debug your problem as the error message hides the real problem.
You can try to do this in your view instead/before displaying the table:

```php
debug($data->toArray());
```

This will explicitely execute the query. So the error should occur at this line and you should get a message describing the real problem.

**Comment by dividedbynothing** [comment]
Ah ha!
Thanks very much for that great tip.... and of course, it revealed that I forgot to change the Order By part from your 'username' to a field in my own table. 

Now it works just fine... thanks VERY much for your quick response.

Cheers,
DBN
