### ISSUE TITLE
Release Tag

### ISSUE THREAD

**Issue by umer936** [ypnos-web/cakephp-datatables#90]
Hello, 

No rush, but can you release a new tag for the current master? That way I can use a tagged version instead of dev-master in my composer.json

Thanks!

**Comment by ypnos-web** [comment]
Hello Umer,

thank you for your contributions and your suggestion. Unfortunately, I do not use or maintain cakephp-datatables anymore. So I feel uncomfortable releasing a new tag. It might give the wrong impression to developers that this is properly maintained software.

I hope you understand.
